version: '3.8'
services:
    api:
        build: ./api
        env_file: ./secrets.env
        ports:
            - "4000:4000"
        container_name: template-api
        depends_on: 
            - db-sql
    vue-ui:
        build: ./webapp
        ports:
            - "8080:8080"
        container_name: template-vue
    db-sql:
        image: postgres
        env_file: ./secrets.env
        ports:
            - "5432:5432"
        container_name: template-sql
        volumes: 
            - ./db/.postgres_data:/var/lib/postgresql/data
            - ./db/sql:/docker-entrypoint-initdb.d
